### ISSUE TITLE
Ask positive & negative words dataset

### ISSUE THREAD

**Issue by geadalfa** [fikisyihab72/Data-Science-Advanced#1]
Hi, your repository is good but can I ask you something? where do you get positive and negative words in Bahasa Indonesia?

**Comment by fikisyihab72** [comment]
Halo, positive & negative words for lexicon based ? you can find them on the internet.

**Comment by geadalfa** [comment]
ohh I see I've found them, but I can't find the neutral words... Is there any Bahasa Indonesia neutral word library out there?
